GET http://localhost:3333/api/tasks

######

POST http://localhost:3333/api/tasks
Content-Type: application/json

{
  "title": "string",
  "description": "string"
}

######

DELETE http://localhost:3333/api/tasks/:id 

######

PUT http://localhost:3333/api/tasks/:id
Content-Type: application/json

{
  "title": "string",
  "description": "string",
  "completed": true,
  "isActive": true
}

######
